server:
  port: 8888

spring:
  application:
    name: order-consumer

eureka:
  client:
    #    默认为true：自动注册到 注册中心
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10086/eureka/