server:
  #  如果没有配置制定port，则默认为10086
  port: ${port:10086}

spring:
  application:
    #    eureka 中作为 serviceId
    name: eureka-server-center

eureka:
  instance:
    hostname: localhost
  #    ip-address: 127.0.0.1
  client:
    #    高可用注册中心，其实就是把EurekaServer自己也作为一个服务，注册到其它EurekaServer上，
    #    这样多个 EurekaServer之间就能互相发现对方，从而形成集群
    register-with-eureka: false #    注册中心，自己的服务不注册、不发现
    fetch-registry: false   #    注册中心，自己的服务不注册、不发现
    service-url:
      #      注册中心的地址，集群部署时 写多个用,隔开
      defaultZone: http://127.0.0.1:10086/eureka/
#      defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka/}
