server:
  port: ${port:9999}

spring:
  application:
    name: user-service
eureka:
  client:
    #    默认为true：自动注册到 注册中心
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    #    prefer-ip-address: true
    #    服务续约(renew)的间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    #    服务失效时间，默认值90秒
    lease-expiration-duration-in-seconds: 90

